name: Deploy to AWS

on:
  push:
    branches: [ main ]  # 只在 main 分支推送时触发
  # 如果需要在 PR 合并时部署，可以添加：
  # pull_request:
  #   types: [closed]
  #   branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ Asia Pacific (Hong Kong) ap-east-1 }}
          
      - name: Deploy to S3
        run: |
          # 同步网站文件到 S3 存储桶
          aws s3 sync . s3://mytvbprojectbucket-1 \
            --exclude ".git/*" \
            --exclude ".gitignore" \
            --exclude ".github/*" \
            --delete  # 删除 S3 上不存在于本地的文件
          
