name: Deploy to AWS

on:
  push:
    branches: [ main ]
  # 如果需要 PR 合并时触发：
  # pull_request:
  #   types: [closed]
  #   branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}  # 使用 GitHub Secret 存储 AWS Region
          
      - name: Download files from source S3 bucket
        run: |
          # 从另一个 S3 存储桶下载文件
          aws s3 sync s3://${{ secrets.S3_BUCKET_OJ_NAME }}/ ./workspaces/1D_TVB_Project/app/images
          
      - name: Deploy to target S3 bucket
        run: |
          # 同步文件到目标 S3 存储桶
          aws s3 sync . s3://${{ secrets.S3_BUCKET_NAME }} \
            --exclude ".git/*" \
            --exclude ".gitignore" \
            --exclude ".github/*" \
            --delete
